DROP DATABASE IF  EXISTS LOGIN;
CREATE DATABASE LOGIN;

USE LOGIN;


CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL
);

INSERT INTO users (username, password) VALUES ('user', 'pass');
